jobs:
  - name: spit-logs
    plan:
      - task: spit
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: mingrammer/flog
          run:
            path: flog
            args: ["-n", "100000"] # 100k plain log lines create noticable lag on a locally runing concourse when logs are loaded in the web ui.
